version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - n1

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ZOOKEEPER_SASL_ENABLED: 'false'
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/configs/jaas-kafka-server.conf"
    volumes:
      - ./src/main/resources/kafka/kafka-config:/etc/kafka/configs
    networks:
      - n1

  postgres-book-accounting-system:
    build: src/main/resources/db
    volumes:
      - data-postgres-book-accounting-system:/var/lib/postgresql/data
    networks:
      - n1

  book-accounting-system:
    build: .
    ports:
      - "8080:8080"
    networks:
      - n1
    depends_on:
      - kafka
      - postgres-book-accounting-system

networks: 
  n1:
    driver: bridge

volumes:
  data-postgres-book-accounting-system: