version: "3.9"
services:
  postgres-book-accounting-system:
    build: src/main/resources/db
    volumes:
      - data-postgres-book-accounting-system:/var/lib/postgresql/data
    networks:
      - n1

  book-accounting-system:
    build: .
    ports:
      - "8080:8080"
    networks:
      - n1
    depends_on:
      - postgres-book-accounting-system

networks: 
  n1:
    driver: bridge

volumes:
  data-postgres-book-accounting-system: