SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE request;
SET REFERENTIAL_INTEGRITY TRUE;
ALTER SEQUENCE request_request_id_seq RESTART WITH 1;

SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE book_history;
SET REFERENTIAL_INTEGRITY TRUE;
ALTER SEQUENCE book_history_book_history_id_seq RESTART WITH 1;

SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE book_storage;
SET REFERENTIAL_INTEGRITY TRUE;
ALTER SEQUENCE book_storage_book_storage_id_seq RESTART WITH 1;

SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE user_;
SET REFERENTIAL_INTEGRITY TRUE;
ALTER SEQUENCE user_user_id_seq RESTART WITH 1;

SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE book;
SET REFERENTIAL_INTEGRITY TRUE;
ALTER SEQUENCE book_book_id_seq RESTART WITH 1;

